FROM node:20.1.0-alpine3.16

WORKDIR /app/frontend

# Copy the frontend files to the container
COPY ./frontend /app/frontend

# Install dependencies
RUN npm install
RUN pnpm install
# Expose port 3000
EXPOSE 3000

# Start the frontend
CMD ["npm", "start"]
